name: Test Action

on: [push]  # Runs when code is pushed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: 22f3002112@ds.study.iitm.ac.in
        run: echo "Hello, world!"
